### ISSUE TITLE
Initial load doesn't apply correct column widths

### ISSUE THREAD

**Issue by Tklaversma** [DataTables/Responsive#56] opened 2015-11-09 14:38 UTC
Hi Allen,

When DataTables is loaded it's show the table with incorrect column widths (see [here](http://pasteboard.co/20DUuP8A.jpg)).
When I resize the browser window, it's automatically show the correct widths (see [here](http://pasteboard.co/20DSG7yL.jpg)).

Since I updated my DataTables to 1.10.10, Responsive to 2.0.0 and Buttons to 1.1.0 this is happening..

Hope you can help me out.

Regards,
TK

**Comment by DataTables** [comment] 2015-11-09 17:37
Can you link to a test page showing the issue so I can try to debug what is happening please.

**Comment by Tklaversma** [comment] 2015-11-10 08:43
@DataTables [Here](http://jsfiddle.net/ebRXw/896/) you can find a fully working example. I used the Download builder to create the **debug version** of the version I'm using.

Note that before I updated my DataTables to 1.10.10, Responsive to 2.0.0 and Buttons to 1.1.0, the buttons were as close to eachother as after the window resize. So personally I think Responsive "forgets" to (re)calculate column widths or something..

Thanks for helping me out!

**Comment by DataTables** [comment] 2015-11-10 11:53
Thanks for the link. I'll take a look into it as soon as I can.

**Comment by Tklaversma** [comment] 2015-11-10 11:54
@DataTables Thanks for taking a look at it. I'll await your response.

**Comment by DataTables** [comment] 2015-11-10 16:02
The issue is related to the use of the `never` class - that is really legacy now and should no longer be used in v2.

Add the following the DataTables columns initialisation and it helps:

                    {
                        targets : 'never',
                        visible: false
                    }

It isn't quite right, but I'll continue to look into it.

**Comment by Tklaversma** [comment] 2015-11-10 16:05
Thanks for letting me know. I'll update my code than not to use ```never```anymore. But what is the new way of using it? Your example or is that a workaround?

**Comment by DataTables** [comment] 2015-11-10 16:07
Use the DataTables column visibility controls - the `never` class was always a workaround. 

However, it looks like there is still an error, when Responsive is required on load.

**Comment by Tklaversma** [comment] 2015-11-10 16:19
Ah ok. Thank you for showing me the correct way of using "never" (or what ever I want to call it :P).
Good luck with fixing the error in Responsive.

Greetings!

**Comment by DataTables** [comment] 2015-11-10 16:21
Going to reopen so I remember to fix this... :-)

**Comment by DataTables** [comment] 2016-01-08 15:11
Closing again as a result of the fix for #66.

**Closed by DataTables** 2016-01-08 15:11 UTC
