### ISSUE TITLE
Ignore option bVisible: false

### ISSUE THREAD

**Issue by ikarius6** [DataTables/Responsive#42] opened 2015-07-27 02:21 UTC
When the responsive: true option is used, the bVisible of aoColumns is completly ignored.

**Comment by DataTables** [comment] 2015-07-27 07:40
I had thought that there was already an issue for this, but apparently not (there are however several forum threads about it). Basically the issue is that Responsive uses the column visibility controls itself to show / hide columns as needed, hence why they are not currently compatible.

This will be addressed in a future version.

**Comment by DataTables** [comment] 2015-09-30 14:00
I've fixed this now with 728a09290b6f1e4d840b8c1bf4642322b9966788. It will be released as part of Responsive v2, which should be around two weeks time.

**Closed by DataTables** 2015-09-30 14:00 UTC

**Comment by ikarius6** [comment] 2015-09-30 16:29
Thank you!
