### ISSUE TITLE
 The Responsive extension can't work with the datatables rendered with javascript soured data

### ISSUE THREAD

**Issue by libillgithub** [DataTables/Responsive#23] opened 2015-02-02 11:06 UTC
The Responsive extension can't work with the datatables rendered with javascript soured data.

**Comment by DataTables** [comment] 2015-02-02 11:13
Please link to a test case showing the issue. It should work just fine as the mechanism is the same as for [ajax sourced data](http://datatables.net/extensions/responsive/examples/initialisation/ajax.html).

Allan

**Comment by cdaringe** [comment] 2015-03-10 20:08
I use this regularly.  This is not a bug (1.10.4 & 1.10.5 @least).  Should be closed.  @libillgithub, put up a fiddle and I can help you out if allan is slammed.

**Comment by DataTables** [comment] 2015-04-01 15:13
No test case provided - closing.

**Closed by DataTables** 2015-04-01 15:13 UTC
