### ISSUE TITLE
Transparency with Scroller & Tabs & scrollCollapse

### ISSUE THREAD

**Issue by MacTwister** [DataTables/Responsive#70] opened 2015-11-27 16:06 UTC
I am developing an application where I have four tables each behind a bootstrap tab on one page. One of the tables has few rows, so I enabled scroll collapse and it causes all the tables not to render the correct width for the columns when I first navigate to the tab. If I navigate to the tab a second time, everything is corrected and looks good. See my jsfiddle for an example, even when I disable scrollCollapse I still have column width issue, so maybe its not fully related to that. 

http://jsfiddle.net/wyxL75xt/

**Update**: Also when you first click the 2nd tab, you notice a lot of space with no rows (transparent), and if you try to scroll down for more records, it does some weird stuff (ie no fill the container with rows).

**Comment by DataTables** [comment] 2015-11-27 17:03
Thanks for the test case. I would be reasonably certain that this is a duplicate of #56 and #66.

I'll try to make some time to look into it next week.

The Scroller issue is definitely a separate bug.

**Comment by AllanJard** [comment] 2023-11-24 11:21
Missed this when closing #66.

**Closed by AllanJard** 2023-11-24 11:21 UTC
