### ISSUE TITLE
Responsive makes columns invisible for export even when vertically uncollapsed

### ISSUE THREAD

**Issue by legshooter** [DataTables/Responsive#90] opened 2016-08-04 22:34 UTC
Hey,

I guess this is kind of overlapping with `Buttons`, I wasn't so sure where to post this.

I am using `exportOptions.columns: ':visible:not(.control):not(.select-checkbox)'` on all my export buttons (as mentioned in https://github.com/DataTables/Buttons/issues/102), but unfortunately when `Responsive` collapses columns they become invisible, even though the user still has them as visible through the use of `colvis`, obviously resulting in them being excluded from the export.

On second thought, I figured this might make sense, because there's a `display: $.fn.dataTable.Responsive.display.childRowImmediate` option that collapses the columns horizontally, but keeps them uncollapsed vertically. Unfortunately, it appears as though the result is the same - Even though the data is now visible on the screen, it is still being excluded from the export due to the `:visible...` selector.

Is this intended behaviour? Is there a technical barrier to change this? Any chance for a fix/enhancement?

The ultimate goal is to let users easily export the columns they want through the use of `colvis` and the export buttons, and enjoy the same flexibility on smaller screens, without `Responsive` interfering and forcing exclusion of columns due to screen size.

Thanks.

**Comment by DataTables** [comment] 2016-08-05 08:09
As you say it is due to the `:visible` selector which is based on the column, not any child row display, so yes, this is the expected behaviour. You would need to use some other selector to get the behaviour you want I'm afraid.

**Comment by legshooter** [comment] 2017-01-28 03:31
For anyone interested, here's the hack I came up with:
```javascript
buttons: [
    {
        name: 'print',
        extend: 'print',
        exportOptions: {
            rows: ...
            columns: ...
        },
        action: function(e, dt, button, config) {
            responsiveToggle(dt);
            $.fn.DataTable.ext.buttons.print.action(e, dt, button, config);
            responsiveToggle(dt);
        }
    },
    ...
]
```

Unfortunately, the API has no built in toggle for Responsive, so I went with:

```javascript
responsiveToggle(dt) {
    $(dt.table().header()).find('th').toggleClass('all');
    dt.responsive.rebuild();
    dt.responsive.recalc();
}
```

Of course If you already use `.all` this can be problematic.

Combined with what I wrote earlier, this lets the user fully control columns visibility for exporting and blocks Responsive from interfering, while keeping the UI intact.

Would love to see something implemented along these lines instead of relying on this hack.

**Comment by lenamtl** [comment] 2017-11-28 16:20
Hi, 
I'm having the same problem 

i'm trying to use your code
and  it's give me an error : Uncaught SyntaxError: Unexpected identifier

my table id is like this, what do I need to change in your code to make this work with mine?
`var table7 = $('#users-list').DataTable({
`
 and where do you put this code?
```
responsiveToggle(dt) {
    $(dt.table().header()).find('th').toggleClass('all');
    dt.responsive.rebuild();
    dt.responsive.recalc();
}
```
Or if you found a better solution since your last post, let me know
Thanks

**Comment by lenamtl** [comment] 2017-11-30 18:09
I finally figure out where to put the code function datatables.js

```
function responsiveToggle(dt) {
   $(dt.table().header()).find('th').toggleClass('all');
   dt.responsive.rebuild();
   dt.responsive.recalc();
}
```

Hope that won't break anything

**Comment by khagesh007** [comment] 2018-11-28 10:01
This is working fine i have tested. But only for print option other export methods are not selecting that columns which are not visible in responsive mode.

` buttons: [
                          {
                                        extend: 'print',
                                        exportOptions: {
                                            columns: ':visible'
                                        },
                              action: function(e, dt, button, config) {
                            responsiveToggle(dt);
                            $.fn.DataTable.ext.buttons.print.action(e, dt, button, config);
                            responsiveToggle(dt);
                            }
                                    }`

**Comment by lenamtl** [comment] 2020-08-16 13:24
Hi, 
This bug is still present in the latest Datatables but the fix is no loguer working any clue how to fix this?

I'm trying to update from Datatables 1.10.11 but this fix is no loguer working and is very important so the user need to export all the column not only the visible ones.

**Comment by DataTables** [comment] 2020-08-17 07:25
Can you link to a test case showing the issue please? My note above says that it is working as expected in the original case described. So I'd need a test case showing the issue to be able to debug it.

**Comment by lenamtl** [comment] 2020-08-19 14:34
Go to https://jsfiddle.net/lenamtl/o8se63fw/
Resize the table so you can see name, office and tools columns then export CSV or Copy
It will export only the visible (from responsive view) columns, not all visible columns from the table.

The fix provided https://github.com/DataTables/Responsive/issues/90#issuecomment-442389478
was working fine with Datatables 1.10.11 and allow to export all visibe columns

**Comment by DataTables** [comment] 2020-08-19 14:42
That seems correct to me since you have explicitly told it to only export visible columns:

> columns: [':visible:not(.not-export-col):not(.hidden)'],

**Comment by lenamtl** [comment] 2020-08-24 14:20
Hi,

No this is not ok as the toggle items should be exported (if they would be visible if not toggle), and we don't want to export hidden items. 

Why this old fix is no longuer working with the new version?

this was added to datatables main script page completely at the beginning of the js file
```
function responsiveToggle(dt) {
            $(dt.table().header()).find('th').toggleClass('all');
            dt.responsive.rebuild();
            dt.responsive.recalc();
        }

```
and this added to buttons: block

```
buttons: [
                     {
                                 extend: 'print',
                                 exportOptions: {
                                            columns: ':visible'
                                        },
                              
                             action: function(e, dt, button, config) {
                                     responsiveToggle(dt);
                                     $.fn.DataTable.ext.buttons.print.action(e, dt, button, config);
                                     responsiveToggle(dt);
                                 }
                   }
]
```

How would you fix that?

**Comment by ZankrutThakkar** [comment] 2021-04-14 21:03
> Hi,
> 
> No this is not ok as the toggle items should be exported (if they are visible when not toggle), and we don't want to export hidden items.
> 
> Why this old fix is no longuer working with the new version?
> How would you fix that?
> 
> this was added to datatables main script page completely at the beginning of the js file
> 
> ```
> function responsiveToggle(dt) {
>             $(dt.table().header()).find('th').toggleClass('all');
>             dt.responsive.rebuild();
>             dt.responsive.recalc();
>         }
> ```
> 
> and this added to buttons: block
> 
> ```
> buttons: [
>                      {
>                                  extend: 'print',
>                                  exportOptions: {
>                                             columns: ':visible'
>                                         },
>                               
>                              action: function(e, dt, button, config) {
>                                      responsiveToggle(dt);
>                                      $.fn.DataTable.ext.buttons.print.action(e, dt, button, config);
>                                      responsiveToggle(dt);
>                                  }
>                    }
> ]
> ```
> 
> This is a big issue and prevent me to update...

I am not sure if you were able to figure out or not as this is quite an old post but I wanted to post a solution that worked for me and to anyone who ends up on this post in the future.

datatables ver: 1.10.23, buttons ver: 1.6.5 

$.fn.DataTable.ext.buttons.print.action.call(this,e, dt, button, config);

```
function responsiveToggle(dt) {
            $(dt.table().header()).find('th').toggleClass('all');
            dt.responsive.rebuild();
            dt.responsive.recalc();
        }

buttons: [
                     {
                          extend: 'excelHtml5',
                           exportOptions: {
                                "columns": [":visible:not(.not-export-col):not(.hidden)"]
                            },
                              
                           action: function(e, dt, button, config) {
                                responsiveToggle(dt);
                               $.fn.DataTable.ext.buttons.excelHtml5.action.call(this,e, dt, button, config);
                               responsiveToggle(dt);
                           }
                  }
]
```

above code allowed me to exclude all the columns made hidden using ColVis but include all the column data from responsive (row)

**Comment by lenamtl** [comment] 2021-04-17 16:07
Any news on this problem

**Comment by DataTables** [comment] 2021-04-19 11:24
Sorry - I forgot to look into this at the time. Can you give me a link to a page showing the issue please? It seems to me that the selector used is selecting visible columns that are not marked as not-export-col`. I think I'll need a test case to fully understand this.

**Comment by lenamtl** [comment] 2021-04-21 13:06
Go to https://jsfiddle.net/lenamtl/o8se63fw/
Resize the table so you can see name, office and tools columns then export CSV or Copy
It will export only the visible (from responsive view) columns, not all visible columns from the table.

The fix provided #90 (comment)
was working fine with Datatables 1.10.11 and allow to export all visibe columns

But unfortunately the fix no longuer work with newest Datatables version.
Could you provide a work around, I need a fix for this bug.

**Comment by zant123** [comment] 2021-04-21 13:48
> Hi,
> 
> No this is not ok as the toggle items should be exported (if they are visible when not toggle), and we don't want to export hidden items.
> 
> Why this old fix is no longuer working with the new version?
> How would you fix that?
> 
> this was added to datatables main script page completely at the beginning of the js file
> 
> ```
> function responsiveToggle(dt) {
>             $(dt.table().header()).find('th').toggleClass('all');
>             dt.responsive.rebuild();
>             dt.responsive.recalc();
>         }
> ```
> 
> and this added to buttons: block
> 
> ```
> buttons: [
>                      {
>                                  extend: 'print',
>                                  exportOptions: {
>                                             columns: ':visible'
>                                         },
>                               
>                              action: function(e, dt, button, config) {
>                                      responsiveToggle(dt);
>                                      $.fn.DataTable.ext.buttons.print.action(e, dt, button, config);
>                                      responsiveToggle(dt);
>                                  }
>                    }
> ]
> ```
> 
> This is a big issue and prevent me to update...

You just have to update `$.fn.DataTable.ext.buttons.print.action(e, dt, button, config);` for the latest version and your selector for exportOption needs to be updated.

```
buttons: [
                     {
                                 extend: 'print',
                                 exportOptions: {
                                            columns: [":visible:not(.not-export-col):not(.hidden)"]
                                        },
                              
                             action: function(e, dt, button, config) {
                                     responsiveToggle(dt);
                                     $.fn.DataTable.ext.buttons.print.action.call(this,e, dt, button, config);
                                     responsiveToggle(dt);
                                 }
                   }
]
```
This has been working for me and I am using datatables ver: 1.10.23

I have updated the fiddle for excel export and it seems to be exporting the childrows created using responsive into excel.

https://jsfiddle.net/s3z2e7ak/

**Comment by lenamtl** [comment] 2021-04-21 14:31
Hi, 

Thanks @zant123 

This seems to work fine, I'm very happy now i would be able to update to the newest version

So we just need replacing this 

    $.fn.DataTable.ext.buttons.excelHtml5.action(e, dt, button, config);

 with this 

    $.fn.DataTable.ext.buttons.excelHtml5.action**.call**(**this,** e, dt, button, config);

**Comment by DataTables** [comment] 2021-04-21 14:59
@zant123 Many thanks for noting that ! The `.call( this` is required in order to call the action in the scope of the activating button.

**Closed** 2023-11-24 11:25 UTC
